apiVersion: 1
datasources:
  - name: AwareNet Prometheus
    uid: awarenet-prom
    type: prometheus
    access: proxy
    url: http://127.0.0.1:19090
    isDefault: true
    editable: false
