"""Build the report landing page from the same historical metrics ledger."""
from pathlib import Path
import json
import shutil

ROOT = Path(__file__).resolve().parents[2]
SITE = ROOT/'site'


def main():
    m = json.loads((ROOT/'configs/measurements/report_metrics_revised.json').read_text(encoding='utf-8'))
    times = ''.join(f'<tr><th>{r["label"]}</th><td>{r["uniform"]["mean_round_s"]:.2f}</td><td>{r["widthpath"]["mean_round_s"]:.2f}</td><td>{r["time_reduction_pct"]:.1f}%</td><td>{r["final_accuracy_difference_pp"]:+.2f}%p</td></tr>' for r in m['scenarios'])
    arms = sorted(m['accuracy_200'],key=lambda r: -(r['lam'] or 1000))
    quality = ''.join(f'<tr><th>{"기준선" if r["lam"] is None else "AwareNet λ="+str(r["lam"])}</th><td>{r["mean_round_s"]:.2f}초</td><td>{r["mean_width"]:.3f}</td><td>{r["tail50_accuracy_pct"]:.2f}%</td><td>{r["accuracy_difference_pp"]:+.2f}%p</td></tr>' for r in arms)
    text = '''<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="분할 연합학습의 폭·경로 적응형 스케줄러 AwareNet. 경로 우선 평가와 폭 축소 페널티, KOREN 라운드 시간 및 200라운드 정확도 비교."><title>AwareNet | 분할 연합학습의 모델 폭과 전송 경로를 조절하는 스케줄러</title><link rel="stylesheet" href="style.css"></head>
<body><a class="skip" href="#main">본문으로 건너뛰기</a><header class="site-header"><div class="container header-inner"><a class="brand" href="#">AwareNet</a><nav aria-label="주요 메뉴"><a href="#motivation">연구 문제</a><a href="#system">설계</a><a href="#application">활용</a><a href="#results">시간·정확도</a><a href="evidence.html">원자료</a><a href="assets/report.pdf">보고서 ↗</a></nav></div></header>
<main id="main" class="container">
<section class="opening"><p class="kicker">KOREN NET CHALLENGE · 충남대학교 · 2026.09</p><h1>클라이언트의 모델 폭과 전송 경로를<br class="desktop"> 함께 조절하는 분할 연합학습</h1><p class="subtitle">AwareNet: adaptive width and relay-path scheduling for split federated learning</p>
<div class="opening-grid"><div><h2 class="small-title">프로젝트 요약</h2><p class="abstract">분할 연합학습에서는 클라이언트가 모델 앞부분을, 서버가 뒷부분을 학습한다. 클라이언트의 계산이 느리거나 중간 계산 결과의 전송이 밀리면 전체 학습이 기다리게 된다. <strong>AwareNet은 여유 있는 중계 서버를 먼저 찾고, 그래도 지연이 남으면 CNN의 채널 수를 줄일지 판단한다.</strong> CNN에서는 채널 수로 모델 폭을 조절하므로 계산량과 전송량이 함께 바뀐다. 스케줄러의 시간·정확도는 CNN에서 평가하고, 별도의 LoRA 언어모델 실험으로 분할 학습과 연합 집계를 확인했다.</p><div class="links"><a class="button" href="assets/report.pdf">전면 개정 보고서 · 24쪽</a><a href="evidence.html#E8">핵심 수치·집계 코드</a><a href="https://github.com/sijoon-sung/AwareNet">코드 ↗</a></div></div>
<aside class="overview"><h2 class="small-title">입력 → 결정 → 결과</h2><dl><dt>입력</dt><dd>클라이언트별 계산 시간 · 전송량 · 경로 용량</dd><dt>결정</dt><dd>현재 폭으로 경로 평가 → 시간 이득과 폭 축소 페널티 비교</dd><dt>출력</dt><dd>다음 라운드의 폭 비율 · 중계 서버 · 전송 비율</dd><dt>평가</dt><dd>CNN: 시간·정확도 / LoRA: 분할·집계 실행</dd></dl></aside></div>
<figure class="architecture-preview"><a href="assets/architecture.svg"><img src="assets/architecture.svg" alt="클라이언트 앞부분 모델에서 중계 서버 두 개를 통해 서버로 활성값을 보내고 기울기를 반환하는 구조. 상단 스케줄러가 폭과 경로를 계획한다."></a><figcaption>클라이언트·중계 서버·학습 서버의 데이터 흐름. 경로는 사용할 중계 서버의 조합이다.</figcaption></figure></section>
<section id="motivation"><div class="section-title"><span class="section-id">01</span><h2>폭을 줄이기 전에, 경로로 해결할 수 있는가</h2></div><div class="prose"><p>SFL에서는 서버의 기울기가 돌아와야 클라이언트가 해당 배치의 역전파를 마칠 수 있다. 계산이 느린 클라이언트와 전송이 밀리는 클라이언트가 모두 라운드의 지연 원인이 된다. 두 병목은 같은 대기 시간으로 나타나지만 필요한 조치는 다르다.</p><p>폭 축소는 계산량과 전송량을 함께 줄이며, 학습에 사용하는 모델 용량도 줄인다. 경로 변경은 모델을 유지한 채 중계 경합을 분산한다. 이를 따로 적용하면 우회로 해결할 지연에 폭을 줄이거나, 계산이 느린 클라이언트의 경로만 바꾸게 된다. AwareNet은 <strong>공유 회선 아래의 처리 능력을 평가한 뒤, 남은 지연에 폭 제어를 적용</strong>한다.</p></div><blockquote>경로 재배정으로 모델 폭을 유지할 수 있는가? 남은 지연을 줄이려면 어느 클라이언트의 폭을 얼마나 조정해야 하는가?</blockquote></section>
<section id="channels"><div class="section-title"><span class="section-id">CNN</span><h2>CNN을 쓴 이유: 채널 단위로 모델을 줄일 수 있어서</h2></div>
<div class="prose"><p>CNN에서는 채널 수로 모델 폭을 표현한다. 이 프로젝트는 ResNet-18의 채널 수를 바꾸어 <strong>클라이언트의 계산량과 분할 지점에서 보낼 데이터 크기를 함께 조절</strong>한다. 모델 폭을 조절하는 방법이 채널 수 선택이다. 폭 비율 w는 원래 채널 수 대비 사용하는 비율이다. 예를 들어 원래 128채널에서 폭 비율 w=0.75를 선택하면 96채널을 사용한다.</p><p>계층 분할은 클라이언트와 서버가 어디까지 계산할지를 정하고, 모델 폭 조절은 사용할 채널 수를 정한다. 전송 조각 나누기는 이미 계산한 텐서를 여러 연결로 보내는 방법이다.</p></div>
<figure class="paper-figure"><a href="assets/channels.svg"><img src="assets/channels.svg" alt="계층 분할은 계산 위치, 모델 폭 조절은 채널 수, 조각 나누기는 전송 방식. 채널 128, 96, 64에 따라 활성값 4, 3, 2 MiB."></a><figcaption>배치 32 · cut 2 · FP32의 활성값 크기를 코드의 텐서 모양으로 계산한 예. 반환 기울기도 같은 크기이며, 레이블과 통신 헤더는 제외했다.</figcaption></figure>
<p class="references">용어 확인: <a href="https://terms.tta.or.kr/dictionary/dictionaryView.do?subject=federated+learning">TTA 연합 학습</a> · <a href="https://terms.tta.or.kr/dictionary/dictionaryView.do?word_seq=038620-1">TTA 클라이언트</a> · <a href="https://docs.pytorch.org/docs/stable/generated/torch.nn.Conv2d.html">PyTorch 채널·텐서 정의</a> · <a href="https://proceedings.neurips.cc/paper/2021/file/6aed000af86a084f9cb0264161e29dd3-Paper.pdf">FjORD의 모델 폭</a></p></section>
<section id="system"><div class="section-title"><span class="section-id">02</span><h2>완료 시간을 예측하고, 경로 다음에 폭을 결정한다</h2></div>
<div class="model-box"><div class="formula">t<sub>i</sub>(w<sub>i</sub>, S) = c<sub>i</sub>w<sub>i</sub><sup>γᵢ</sup> + <span class="fraction"><span>8b<sub>i</sub>w<sub>i</sub></span><span>R<sub>i</sub>(S)</span></span> + ε<sub>i</sub></div><div class="model-labels"><span><b>계산 시간</b>클라이언트 성능 × 폭의 영향</span><span><b>전송 시간</b>텐서 바이트 ÷ 공유 전송률</span><span><b>보정</b>관측과 예측의 차이</span></div><p>채널 수를 바꿔 줄어드는 계산 시간과 경로를 바꿔 줄어드는 전송 시간을 초 단위로 비교한다. w는 CNN의 폭 비율이며 b×w는 채널 감소에 따른 전송량이다. λ는 폭 축소 페널티를 정하는 값이다.</p></div>
<div class="two-columns"><div><h3>1. 현재 폭으로 경로 평가</h3><p>허용된 중계 서버 조합을 최대 지연과 평균 지연의 합으로 비교한다. 공유 자원을 지나는 흐름은 용량을 나누어 사용한다. 경로 전환의 이득을 확인하고 라운드별 이동 수를 제한한다.</p></div><div><h3>2. 남은 지연에 폭 제어</h3><p>가장 느린 클라이언트들의 폭을 한 단계 낮춰 보는 후보를 만든다. 예상 시간 감소의 90%가 <strong>λ × 평균 폭 비율 감소량</strong>보다 크면 채택한다. λ가 클수록 모델 폭을 유지하는 선택을 선호한다.</p></div></div>
<figure class="paper-figure"><a href="assets/control.svg"><img src="assets/control.svg" alt="관측, 경로 평가, 폭 선택, 다음 라운드 적용의 네 단계. 망 용량이 변한 라운드에는 폭을 유지한다."></a><figcaption>라운드별 의사결정. 폭은 한 단계씩 변경하고 복귀는 두 번 연속 확인한다.</figcaption></figure>
<p>결정된 연결별 예상 전송률에 따라 텐서 조각을 배분하고, 수신 측은 조각이 모두 도착하면 학습 계산에 전달한다. 관측 용량은 경로 이동에, 설정 용량과 공유 배정은 조각 비율에 사용한다. 전송·환경 설정의 상세 구현은 <a href="evidence.html#E6">구현 자료 E6</a>에 수록했다.</p></section>
<section id="results"><div class="section-title"><span class="section-id">03</span><h2>얼마나 빨라졌고, 정확도는 어떻게 달라졌는가</h2></div>
<p>비교군은 전체 채널·단일 연결·고정 배정의 기준선과 두 연결·폭·경로 제어의 AwareNet이다. 아래 결과는 이 두 시스템 구성의 비교다.</p>
<h3>KOREN · 네 병목 조건의 라운드 시간</h3><p class="condition">HPC의 32 CPU 클라이언트 프로세스 + V100 서버 · KOREN VM 2대 / 논리 중계 4개 · CIFAR-10 · ResNet-18 · 24라운드 × 3시드 × 4조건 × 2정책</p>
<figure class="paper-figure"><a href="assets/time-results.svg"><img src="assets/time-results.svg" alt="정상 24.6%, 트래픽 몰림 42.6%, 연산 지연 40.3%, 용량 변동 26.7% 라운드 시간 단축."></a><figcaption>초기 4라운드를 제외한 실행별 평균을 시드 간 평균했다.</figcaption></figure>
<div class="table-wrap"><table><thead><tr><th>조건</th><th>기준선 (초)</th><th>AwareNet (초)</th><th>시간 단축</th><th>최종 24R 정확도 차이</th></tr></thead><tbody>__TIMES__</tbody></table></div>
<p>트래픽 몰림에서는 중계 서버가 재배정되었고 평균 폭 비율은 0.998이었다. 연산 지연에서는 느린 네 클라이언트의 폭 비율을 0.75로, 나머지 28개를 1.0으로 유지했다. <strong>응용 전송량 감소는 최대 3.12%</strong>로, 시간 단축률과는 다른 양상을 보였다. 전송량뿐 아니라 경합과 완료 지연을 함께 보아야 하는 이유다.</p><p class="note"><a href="evidence.html#E1">E1: 원시 로그·실행 조건</a> · <a href="assets/controller-actions.svg">병목별 실제 동작 그림</a> · 32는 HPC에서 실행한 논리 참여자 수다.</p>
<h3>200라운드 · 폭 축소 페널티에 따른 시간과 정확도</h3><p class="condition">8 CPU 클라이언트 프로세스 · 200라운드 × 2시드 · 정확도: 마지막 50라운드 평균 · CIFAR-10 시험 데이터 앞 2,000개</p>
<figure class="paper-figure"><a href="assets/accuracy-results.svg"><img src="assets/accuracy-results.svg" alt="기준선 19.11초 65.52%, λ280은 15.15초 65.22%, λ70은 12.90초 63.17%, λ18은 8.01초 53.59%. 빈 점은 개별 시드, 채운 점은 평균."></a><figcaption>시간이 짧을수록 왼쪽, 정확도가 높을수록 위쪽이다. 빈 점은 개별 시드, 채운 점은 두 시드 평균이다.</figcaption></figure>
<div class="table-wrap"><table><thead><tr><th>설정</th><th>라운드 시간</th><th>평균 폭 비율</th><th>정확도</th><th>기준선과 차이</th></tr></thead><tbody>__QUALITY__</tbody></table></div>
<p>λ=280은 폭을 유지하며 시간을 <strong>20.7% 줄였고 정확도 차이는 −0.29%p</strong>였다. λ=18은 58.1% 빨랐지만 정확도가 11.93%p 낮았다. 두 시드에서 관측한 시간과 정확도의 절충이다. 같은 느린 클라이언트가 계속 작은 모델을 쓰면 일부 채널에 그 클라이언트의 데이터가 덜 반영될 수 있으므로, 현장 적용에는 추가 평가가 필요하다.</p><p class="note">시간은 초기 4라운드 제외 평균. 두 실험 계열은 자원 조건이 다르며 상세 조건은 보고서 표 3을 따른다. <a href="evidence.html#E7">E7: 축소 실행 원자료</a> · <a href="evidence.html#E8">E8: 정의·시드별 수치·재집계 코드</a></p></section>
<section id="hardware"><div class="section-title"><span class="section-id">04</span><h2>연구망과 실제 장비에서 확인한 실행 조건</h2></div>
<figure class="paper-figure"><a href="assets/testbed.svg"><img src="assets/testbed.svg" alt="HPC의 32 CPU 프로세스와 V100 서버가 KOREN VM 두 대의 네 논리 중계를 통해 실제 TCP로 통신하는 배치."></a><figcaption>KOREN은 원격 VM과 HPC 사이에서 실제 텐서를 전송하고, 같은 배치에서 병목 조건을 바꾸어 평가하는 연구망으로 활용했다.</figcaption></figure>
<h3>LoRA가 등장하는 이유: 언어모델의 분할 학습을 확인하기 위해</h3><div class="prose"><p>CNN 실험에서는 폭·경로 스케줄러를 평가했다. 이어 언어모델에서도 자원이 제한된 클라이언트와 서버가 함께 학습하고 결과를 집계할 수 있는지 확인했다. 이 보조 실험은 학습 파라미터를 줄이는 방법으로 <strong>LoRA(Low-Rank Adaptation)</strong>를 사용했다.</p><p>LoRA는 원래 가중치를 고정하고 추가한 저랭크 행렬을 학습한다. <strong>CNN의 채널 수와 LoRA 랭크 r은 다른 변수다.</strong> CNN 채널 축소는 활성값 크기를 줄이지만, LoRA 랭크만 바꾸면 분할 활성값의 은닉 차원은 유지된다. 랭크는 학습 파라미터와 어댑터 집계량에 영향을 준다.</p></div>
<figure class="paper-figure"><a href="assets/cnn-lora.svg"><img src="assets/cnn-lora.svg" alt="위는 CNN 채널 조절과 기존 고정 랭크 LoRA 실험이다. 아래는 은닉 차원 축소, LoRA 학습, 분할 전송과 경로 제어로 이어지는 후속 검증 순서다."></a><figcaption>CNN의 폭 비율 w와 LoRA의 랭크 r을 구분한다. 아래 LoRA 결과는 기존 고정 랭크 실험이다.</figcaption></figure><div class="prose"><p><strong>모델 폭 축소와 LoRA를 함께 쓰는 확장도 가능하다.</strong> SliceGPT는 언어모델의 은닉 차원을 줄인 뒤 LoRA로 추가 학습한다. AwareNet에서는 고정 축소 모델의 품질과 분할 전송부터 검증하고, 이후 폭 전환과 경로 선택을 연결하는 후속 설계로 정리했다.</p></div><p class="references"><a href="https://arxiv.org/abs/2106.09685">LoRA 원문</a> · <a href="https://arxiv.org/abs/2401.15024">SliceGPT 원문</a> · <a href="evidence.html#E9">용어·구현 근거·확장 설계</a></p>
<div class="two-columns"><article><h3>Jetson · 연산 비용의 실측</h3><p>Orin Nano Super 8GB 한 대에서 Qwen2.5-0.5B LoRA 학습을 FP32, 랭크 32, 배치 1, 길이 256으로 실행했다. 초기 3스텝을 제외하고 전력 모드별 30스텝을 측정했다.</p><table><thead><tr><th>전력 모드</th><th>전체 스텝 중앙값</th></tr></thead><tbody><tr><td>MAXN_SUPER</td><td>554.1 ms</td></tr><tr><td>25W</td><td>608.9 ms</td></tr><tr><td>15W</td><td>903.7 ms</td></tr></tbody></table><p>같은 모델도 전력 모드에 따라 약 1.63배의 시간 차이를 보였다. <a href="evidence.html#E2">90스텝·환경·전력 원기록 E2</a></p></article><article><h3>LoRA · 분할 실행과 연합 집계</h3><p>KOREN VM 두 대의 논리 클라이언트 세 개와 HPC에서 Qwen2.5-0.5B를 랭크 16으로 고정해 16라운드×30스텝 실행했다. 자체 문답 18개에서 단독 학습은 6개, 연합 두 방식은 각각 12개를 맞혔다.</p><p>별도의 7B 실험에서는 전체 모델을 한곳에 두고 LoRA로 학습할 때 메모리가 부족했고, 분할 배치로 10스텝을 진행했다. 장비 비용과 분산 학습 실행을 확인한 보조 자료다. <a href="evidence.html#E4">학습·평가·메모리 원기록 E4</a></p></article></div></section>
<section id="application"><div class="section-title"><span class="section-id">05</span><h2>기대 효과: 병원 등 여러 기관이 함께 전역 모델을 개선하는 환경</h2></div>
<p>병원처럼 데이터를 한곳에 모으기 어려운 기관들이 영상 분류 모델을 함께 학습하는 환경을 생각할 수 있다. 클라이언트의 계산 능력과 통신 상태에 맞춘 스케줄링으로 공동 학습의 대기를 줄이고, 여러 기관의 데이터가 반영된 <strong>전역 모델(global model)을 지속적으로 개선할 기반</strong>을 마련하는 것이 기대 효과다.</p>
<figure class="paper-figure"><a href="assets/application.svg"><img src="assets/application.svg" alt="병원 A의 계산 지연에는 채널 수 조절을, 병원 B의 전송 혼잡에는 중계 경로 변경을 평가한다. 중앙 학습 서버에서 전역 모델을 갱신하는 향후 적용 예시."></a><figcaption>기관별 계산·통신 상태 → 모델 폭·경로 스케줄링 → 공동 학습 지속 → 전역 모델 개선의 기반. 향후 적용 시나리오다.</figcaption></figure>
<div class="two-columns"><div><h3>학습에 맞춘 네트워크 운용</h3><p>클라이언트 계산이 오래 걸리면 채널 수를 줄이는 방안을 평가한다. 중계 구간이 혼잡하고 다른 경로에 여유가 있으면 모델을 유지하며 전송을 분산한다. 공유 회선 용량과 모델 품질을 함께 고려한다.</p></div><div><h3>현장 적용의 평가 기준</h3><p>중계 사용 권한과 관측값 수집을 갖추고, 활성값·기울기의 정보 노출 위험을 별도로 검토한다. 효과는 <strong>목표 성능에 도달하는 시간과 기관별 모델 성능</strong>으로 평가한다. 현재 실측은 KOREN·CIFAR-10과 Jetson·LoRA 실행을 대상으로 한다.</p></div></div><p class="references"><a href="https://doi.org/10.1038/s41591-021-01506-3">기관 간 연합학습 사례: EXAM, Nature Medicine (2021)</a></p></section>
<section id="contribution"><div class="section-title"><span class="section-id">06</span><h2>설계가 이렇게 바뀐 이유</h2></div>
<div class="table-wrap"><table><thead><tr><th>개발 중의 질문</th><th>확인한 문제</th><th>현재 선택</th></tr></thead><tbody><tr><th>대역폭만 나누면 충분한가?</th><td>공유 병목의 용량은 그대로다.</td><td>채널 수로 계산량·전송량도 조절</td></tr><tr><th>왜 중계 서버를 두는가?</th><td>여러 학습 서버의 모델 동기화 비용이 생긴다.</td><td>중계와 뒷부분 학습의 역할을 분리</td></tr><tr><th>왜 경로를 먼저 평가하는가?</th><td>이동 중의 일시적 혼잡에 모델이 줄어들 수 있다.</td><td>이동 후의 예상 시간으로 채널 수 선택</td></tr><tr><th>왜 고정 시간 목표를 바꾸었는가?</th><td>목표에 따라 모델 축소가 과도하거나 전혀 발생하지 않았다.</td><td>시간 감소와 채널 감소 페널티 비교</td></tr></tbody></table></div>
<p class="note"><a href="evidence.html#E9">E9: 방향 검토·다중 경로 설계·컨트롤러 변천 기록과 현재 설명의 연결</a></p><h3>기여와 후속 평가</h3><div class="prose"><p>기여는 <strong>경로를 먼저 평가한 뒤 시간 이득과 폭 축소 페널티를 비교하는 스케줄러</strong>, <strong>KOREN 교란 조건과 실제 제어 선택의 연결</strong>, <strong>시간·정확도를 함께 제시한 설정별 비교</strong>이다. FjORD·FedRolex의 부분 모델 학습, AdaptSFL·SuperSFL의 자원 적응형 SFL 연구를 토대로, 고정된 층 분할에서 폭과 중계 배정을 운용하는 문제에 집중했다.</p><p>다음 평가는 같은 연결 수를 유지한 정책 비교, 목표 정확도 도달 시간, 독립 시드 확대에 집중한다. 현재 제어 범위는 클라이언트 프로그램과 허용된 중계 서버이며, 기관 간 네트워크 규칙의 위임·인증과 OS-Ken 스위치 연동은 후속 통합 대상이다.</p></div>
<p class="references">주요 선행연구: <a href="https://arxiv.org/abs/2102.13451v5">FjORD</a> · <a href="https://arxiv.org/abs/2212.01548v2">FedRolex</a> · <a href="https://arxiv.org/abs/2403.13101v4">AdaptSFL</a> · <a href="https://arxiv.org/abs/2601.02092v2">SuperSFL</a>. 개별 비교와 판본은 보고서 참고문헌을 따른다.</p></section>
<section id="resources"><div class="section-title"><span class="section-id">07</span><h2>보고서와 원자료</h2></div><div class="resource-grid"><a href="assets/report.pdf"><b>전면 개정 보고서 · 24쪽</b><span>요약문 · Ⅰ~Ⅴ장 · 그림 9개 · 표 6개</span></a><a href="evidence.html"><b>원자료 색인 E1–E9</b><span>조건 · 개별 원파일 · ZIP · 집계 코드</span></a><a href="https://github.com/sijoon-sung/AwareNet/blob/awarenet/docs/INDEX.md"><b>문서 목차</b><span>현재 원고와 과거 설계·실험 기록의 연결</span></a><a href="https://github.com/sijoon-sung/AwareNet"><b>공개 소스</b><span>실행 코드 · 원자료 · 보고서 생성 코드</span></a></div>
<details><summary>보조 가상망 실험 · 계측과 재현 자료</summary><p>Linux 가상망에서 TCP 조각 전송과 재조립, 공유 병목을 확인한 한 번의 보조 실험이다. 환경 설정과 패킷·대시보드 원기록을 제공한다.</p><div class="links"><a href="evidence.html#E5">자료 범위 E5</a><a href="assets/lab/report.html">계측 보고</a><a href="assets/lab/capture.pcapng">Wireshark PCAP</a><a href="assets/lab/dashboard.json">Grafana 대시보드</a><a href="assets/lab/reproduce.md">재현 안내</a></div></details></section>
</main><footer class="container"><span>AwareNet · 충남대학교 · KOREN 넷챌린지</span><span>보고서 전면 개정 2026.09.28</span></footer></body></html>
'''.replace('__TIMES__',times).replace('__QUALITY__',quality)
    (SITE/'index.html').write_text(text,encoding='utf-8')
    for src,dst in [('R1_architecture','architecture'),('R2_control','control'),('R3_testbed','testbed'),('R4_time','time-results'),('R5_actions','controller-actions'),('R6_accuracy','accuracy-results'),('R7_channels','channels'),('R8_application','application'),('R9_cnn_lora','cnn-lora')]:
        shutil.copyfile(ROOT/f'output/prose_awarenet/figures/{src}.svg',SITE/f'assets/{dst}.svg')
    shutil.copyfile(ROOT/'output/prose_awarenet/AwareNet_서술형보고서.pdf',SITE/'assets/report.pdf')
    print(json.dumps({'page':'site/index.html','figures':9,'statistics_source':'report_metrics_revised.json'}))


if __name__=='__main__':main()
